version: '3.8'

services:
  # 프론트엔드 프로덕션 설정
  frontend:
    build:
      context: ./excel-relations-front
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://api.example.com # 프로덕션 API URL로 변경 필요
    # 프로덕션에서는 볼륨 마운트 제거하여 성능 최적화

  # 백엔드 프로덕션 설정
  backend:
    build:
      context: ./excel-relations-api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/excel_relations
    # 프로덕션에서는 소스 코드 볼륨 마운트 제거하고 업로드 디렉토리만 유지
    volumes:
      - ./excel-relations-api/uploads:/app/uploads

  # PostgreSQL 프로덕션 설정
  postgres:
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # OpenRouteService 프로덕션 설정
  openroute:
    restart: always

volumes:
  postgres_data_prod: 