version: '3.8'

services:
  # 프론트엔드 서비스
  frontend:
    build: ./excel-relations-front
    container_name: excel-relations-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./excel-relations-front:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000
    restart: unless-stopped

  # 백엔드 서비스
  backend:
    build: ./excel-relations-api
    container_name: excel-relations-backend
    ports:
      - "5000:5000"
    volumes:
      - ./excel-relations-api:/app
      - /app/node_modules
      - ./excel-relations-api/uploads:/app/uploads
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/excel_relations
    restart: unless-stopped

  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: excel-relations-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=excel_relations
    restart: unless-stopped

  # OpenRouteService
  openroute:
    extends:
      file: ./openroute/docker-compose.yml
      service: ors-app
    container_name: excel-relations-openroute
    restart: unless-stopped

volumes:
  postgres_data: 