version: '3.8'

services:
  # 프론트엔드 개발 설정
  frontend:
    build: 
      context: ./excel-relations-front
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./excel-relations-front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000

  # 백엔드 개발 설정
  backend:
    build: 
      context: ./excel-relations-api
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./excel-relations-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/excel_relations

  # PostgreSQL 개발 설정
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data_dev: 