version: '3.8'

services:
  ors-app:
    build:
      context: ./
    container_name: ors-app
    ports:
      - "8081:8082"
      - "9001:9001"
    image: openrouteservice/openrouteservice:v8.2.0
    volumes:
      - ./ors-docker:/home/ors
    environment:
      REBUILD_GRAPHS: True
      CONTAINER_LOG_LEVEL: INFO
      
      # 메모리 설정 (8GB 시스템에 맞춤)
      XMS: 8g
      XMX: 16g
      CATALINA_OPTS: "-Dserver.port=8082 -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
      
      ORS_CONFIG_LOCATION: /home/ors/config/ors-config.yml