ors:
  engine:
    source_file: /home/ors/files/south-korea-latest.osm.pbf
    graphs_root_path: /home/ors/graphs
    elevation:
      cache_path: /home/ors/elevation_cache
    profiles:
      car:
        enabled: true
        profile: driving-car
        build:
          source_file: /home/ors/files/south-korea-latest.osm.pbf
      foot-walking:
        enabled: true
        profile: foot-walking  
        build:
          source_file: /home/ors/files/south-korea-latest.osm.pbf
      cycling-regular:
        enabled: true
        profile: cycling-regular
        build:
          source_file: /home/ors/files/south-korea-latest.osm.pbf

logging:
  level:
    org.heigit: INFO
    org.springframework: INFO